### PR TITLE
feat: Moved all bepu libraries into their own package

### PR DESCRIPTION
**Pull request by Doprez**
This should solve some issues for people who are using the new Bepu packages until a proper nuget gets released.

Until that package gets released, having both the community toolkit and the new bepu package causes issues where the compiler cant resolve the right type and causes inconsistent errors.

### CODE REVIEW

**Comment by VaclavElias** [comment]
Do you want me to releaese new NuGet packages ASAP, or can it wait till weekend?

**Comment by Doprez** [comment]
It can wait, I think Im the only one who has complained so far and I can just use this branches source if I need to.

**Comment by VaclavElias** [comment]
Ok, I can still merge it. Let me know when it is ready. I have to update then GitHub Action, to create new packages. 

I have to show it to you eventually, so you could deploy the packages yourself 💪🙂

**Comment by VaclavElias** [comment]
Thank you Sir!

**Pull request merged**
